access_ip   = "0.0.0.0/0"
db_name     = "rancher"
db_username = "mike"
db_password = "kasunraj123"
instance_count = "2"
instance_type = "t3.micro"
public_key_path = "/Users/kasunrajapakse/.ssh/k3nodeskey.pub"
key_name = "k3nodeskey"